// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthRequest is empty
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

// HealthResponse indicates server health
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PoweronRequest contains the path to model directory or individual file paths
type PoweronRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Path                 string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                               // Path to model directory (optional if individual paths provided)
	ModelPath            string                 `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`                                    // Path to model file (optional, takes priority over path)
	LexicalShortlistPath string                 `protobuf:"bytes,3,opt,name=lexical_shortlist_path,json=lexicalShortlistPath,proto3" json:"lexical_shortlist_path,omitempty"` // Path to lexical shortlist file (optional, takes priority over path)
	VocabularyPath       string                 `protobuf:"bytes,4,opt,name=vocabulary_path,json=vocabularyPath,proto3" json:"vocabulary_path,omitempty"`                     // Path to vocabulary file (optional, merged with vocabulary_paths)
	VocabularyPaths      []string               `protobuf:"bytes,5,rep,name=vocabulary_paths,json=vocabularyPaths,proto3" json:"vocabulary_paths,omitempty"`                  // Paths to vocabulary files (optional, merged with vocabulary_path)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PoweronRequest) Reset() {
	*x = PoweronRequest{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweronRequest) ProtoMessage() {}

func (x *PoweronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweronRequest.ProtoReflect.Descriptor instead.
func (*PoweronRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *PoweronRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PoweronRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *PoweronRequest) GetLexicalShortlistPath() string {
	if x != nil {
		return x.LexicalShortlistPath
	}
	return ""
}

func (x *PoweronRequest) GetVocabularyPath() string {
	if x != nil {
		return x.VocabularyPath
	}
	return ""
}

func (x *PoweronRequest) GetVocabularyPaths() []string {
	if x != nil {
		return x.VocabularyPaths
	}
	return nil
}

// PoweronResponse indicates whether the engine loaded successfully
type PoweronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoweronResponse) Reset() {
	*x = PoweronResponse{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweronResponse) ProtoMessage() {}

func (x *PoweronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweronResponse.ProtoReflect.Descriptor instead.
func (*PoweronResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PoweronResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PoweronResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PoweroffRequest contains shutdown parameters
type PoweroffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int32                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`   // seconds to wait before shutdown
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // force shutdown without waiting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoweroffRequest) Reset() {
	*x = PoweroffRequest{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweroffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweroffRequest) ProtoMessage() {}

func (x *PoweroffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweroffRequest.ProtoReflect.Descriptor instead.
func (*PoweroffRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *PoweroffRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PoweroffRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// PoweroffResponse indicates shutdown status
type PoweroffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoweroffResponse) Reset() {
	*x = PoweroffResponse{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweroffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweroffResponse) ProtoMessage() {}

func (x *PoweroffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweroffResponse.ProtoReflect.Descriptor instead.
func (*PoweroffResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *PoweroffResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PoweroffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RebootRequest contains reboot parameters
type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int32                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`   // seconds to wait before reboot
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // force reboot without waiting for active requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *RebootRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RebootRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RebootResponse indicates reboot status
type RebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootResponse) Reset() {
	*x = RebootResponse{}
	mi := &file_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootResponse) ProtoMessage() {}

func (x *RebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootResponse.ProtoReflect.Descriptor instead.
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *RebootResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RebootResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReadyRequest is empty
type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{8}
}

// ReadyResponse indicates whether an engine is loaded
type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// ComputeRequest contains the text to translate
type ComputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Html          bool                   `protobuf:"varint,2,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_proto_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ComputeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ComputeRequest) GetHtml() bool {
	if x != nil {
		return x.Html
	}
	return false
}

// ComputeResponse contains the translated text
type ComputeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TranslatedText string                 `protobuf:"bytes,3,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_proto_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ComputeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ComputeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComputeResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\n" +
	"translator\"\x0f\n" +
	"\rHealthRequest\">\n" +
	"\x0eHealthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x01\n" +
	"\x0ePoweronRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x124\n" +
	"\x16lexical_shortlist_path\x18\x03 \x01(\tR\x14lexicalShortlistPath\x12'\n" +
	"\x0fvocabulary_path\x18\x04 \x01(\tR\x0evocabularyPath\x12)\n" +
	"\x10vocabulary_paths\x18\x05 \x03(\tR\x0fvocabularyPaths\"?\n" +
	"\x0fPoweronResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x0fPoweroffRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x05R\x04time\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"@\n" +
	"\x10PoweroffResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\rRebootRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x05R\x04time\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\">\n" +
	"\x0eRebootResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fReadyRequest\"S\n" +
	"\rReadyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"8\n" +
	"\x0eComputeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x02 \x01(\bR\x04html\"h\n" +
	"\x0fComputeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ftranslated_text\x18\x03 \x01(\tR\x0etranslatedText2\xf0\x03\n" +
	"\x11TranslatorService\x12?\n" +
	"\x06Health\x12\x19.translator.HealthRequest\x1a\x1a.translator.HealthResponse\x12B\n" +
	"\aPoweron\x12\x1a.translator.PoweronRequest\x1a\x1b.translator.PoweronResponse\x12E\n" +
	"\bPoweroff\x12\x1b.translator.PoweroffRequest\x1a\x1c.translator.PoweroffResponse\x12?\n" +
	"\x06Reboot\x12\x19.translator.RebootRequest\x1a\x1a.translator.RebootResponse\x12<\n" +
	"\x05Ready\x12\x18.translator.ReadyRequest\x1a\x19.translator.ReadyResponse\x12B\n" +
	"\aCompute\x12\x1a.translator.ComputeRequest\x1a\x1b.translator.ComputeResponse\x12L\n" +
	"\rComputeStream\x12\x1a.translator.ComputeRequest\x1a\x1b.translator.ComputeResponse(\x010\x01B(Z&github.com/xxnuo/MTranCore/proto;protob\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_worker_proto_goTypes = []any{
	(*HealthRequest)(nil),    // 0: translator.HealthRequest
	(*HealthResponse)(nil),   // 1: translator.HealthResponse
	(*PoweronRequest)(nil),   // 2: translator.PoweronRequest
	(*PoweronResponse)(nil),  // 3: translator.PoweronResponse
	(*PoweroffRequest)(nil),  // 4: translator.PoweroffRequest
	(*PoweroffResponse)(nil), // 5: translator.PoweroffResponse
	(*RebootRequest)(nil),    // 6: translator.RebootRequest
	(*RebootResponse)(nil),   // 7: translator.RebootResponse
	(*ReadyRequest)(nil),     // 8: translator.ReadyRequest
	(*ReadyResponse)(nil),    // 9: translator.ReadyResponse
	(*ComputeRequest)(nil),   // 10: translator.ComputeRequest
	(*ComputeResponse)(nil),  // 11: translator.ComputeResponse
}
var file_proto_worker_proto_depIdxs = []int32{
	0,  // 0: translator.TranslatorService.Health:input_type -> translator.HealthRequest
	2,  // 1: translator.TranslatorService.Poweron:input_type -> translator.PoweronRequest
	4,  // 2: translator.TranslatorService.Poweroff:input_type -> translator.PoweroffRequest
	6,  // 3: translator.TranslatorService.Reboot:input_type -> translator.RebootRequest
	8,  // 4: translator.TranslatorService.Ready:input_type -> translator.ReadyRequest
	10, // 5: translator.TranslatorService.Compute:input_type -> translator.ComputeRequest
	10, // 6: translator.TranslatorService.ComputeStream:input_type -> translator.ComputeRequest
	1,  // 7: translator.TranslatorService.Health:output_type -> translator.HealthResponse
	3,  // 8: translator.TranslatorService.Poweron:output_type -> translator.PoweronResponse
	5,  // 9: translator.TranslatorService.Poweroff:output_type -> translator.PoweroffResponse
	7,  // 10: translator.TranslatorService.Reboot:output_type -> translator.RebootResponse
	9,  // 11: translator.TranslatorService.Ready:output_type -> translator.ReadyResponse
	11, // 12: translator.TranslatorService.Compute:output_type -> translator.ComputeResponse
	11, // 13: translator.TranslatorService.ComputeStream:output_type -> translator.ComputeResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
