// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslatorService_Health_FullMethodName      = "/translator.TranslatorService/Health"
	TranslatorService_Trans_FullMethodName       = "/translator.TranslatorService/Trans"
	TranslatorService_TransStream_FullMethodName = "/translator.TranslatorService/TransStream"
	TranslatorService_Exit_FullMethodName        = "/translator.TranslatorService/Exit"
)

// TranslatorServiceClient is the client API for TranslatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TranslatorService provides translation capabilities
type TranslatorServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Trans(ctx context.Context, in *TransRequest, opts ...grpc.CallOption) (*TransResponse, error)
	TransStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransRequest, TransResponse], error)
	Exit(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error)
}

type translatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslatorServiceClient(cc grpc.ClientConnInterface) TranslatorServiceClient {
	return &translatorServiceClient{cc}
}

func (c *translatorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Trans(ctx context.Context, in *TransRequest, opts ...grpc.CallOption) (*TransResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Trans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) TransStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransRequest, TransResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslatorService_ServiceDesc.Streams[0], TranslatorService_TransStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransRequest, TransResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_TransStreamClient = grpc.BidiStreamingClient[TransRequest, TransResponse]

func (c *translatorServiceClient) Exit(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Exit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslatorServiceServer is the server API for TranslatorService service.
// All implementations must embed UnimplementedTranslatorServiceServer
// for forward compatibility.
//
// TranslatorService provides translation capabilities
type TranslatorServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Trans(context.Context, *TransRequest) (*TransResponse, error)
	TransStream(grpc.BidiStreamingServer[TransRequest, TransResponse]) error
	Exit(context.Context, *ExitRequest) (*ExitResponse, error)
	mustEmbedUnimplementedTranslatorServiceServer()
}

// UnimplementedTranslatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslatorServiceServer struct{}

func (UnimplementedTranslatorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTranslatorServiceServer) Trans(context.Context, *TransRequest) (*TransResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trans not implemented")
}
func (UnimplementedTranslatorServiceServer) TransStream(grpc.BidiStreamingServer[TransRequest, TransResponse]) error {
	return status.Error(codes.Unimplemented, "method TransStream not implemented")
}
func (UnimplementedTranslatorServiceServer) Exit(context.Context, *ExitRequest) (*ExitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedTranslatorServiceServer) mustEmbedUnimplementedTranslatorServiceServer() {}
func (UnimplementedTranslatorServiceServer) testEmbeddedByValue()                           {}

// UnsafeTranslatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslatorServiceServer will
// result in compilation errors.
type UnsafeTranslatorServiceServer interface {
	mustEmbedUnimplementedTranslatorServiceServer()
}

func RegisterTranslatorServiceServer(s grpc.ServiceRegistrar, srv TranslatorServiceServer) {
	// If the following call panics, it indicates UnimplementedTranslatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslatorService_ServiceDesc, srv)
}

func _TranslatorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Trans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Trans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Trans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Trans(ctx, req.(*TransRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_TransStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslatorServiceServer).TransStream(&grpc.GenericServerStream[TransRequest, TransResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_TransStreamServer = grpc.BidiStreamingServer[TransRequest, TransResponse]

func _TranslatorService_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Exit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Exit(ctx, req.(*ExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranslatorService_ServiceDesc is the grpc.ServiceDesc for TranslatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translator.TranslatorService",
	HandlerType: (*TranslatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TranslatorService_Health_Handler,
		},
		{
			MethodName: "Trans",
			Handler:    _TranslatorService_Trans_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _TranslatorService_Exit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransStream",
			Handler:       _TranslatorService_TransStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/worker.proto",
}
