// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadyRequest is empty
type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

// ReadyResponse indicates whether an engine is loaded
type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// PoweroffRequest contains shutdown parameters
type PoweroffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int32                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`   // seconds to wait before shutdown
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // force shutdown without waiting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoweroffRequest) Reset() {
	*x = PoweroffRequest{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweroffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweroffRequest) ProtoMessage() {}

func (x *PoweroffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweroffRequest.ProtoReflect.Descriptor instead.
func (*PoweroffRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *PoweroffRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PoweroffRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// PoweroffResponse indicates shutdown status
type PoweroffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoweroffResponse) Reset() {
	*x = PoweroffResponse{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoweroffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoweroffResponse) ProtoMessage() {}

func (x *PoweroffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoweroffResponse.ProtoReflect.Descriptor instead.
func (*PoweroffResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PoweroffResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PoweroffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ComputeRequest contains the text to translate
type ComputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Html          bool                   `protobuf:"varint,2,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ComputeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ComputeRequest) GetHtml() bool {
	if x != nil {
		return x.Html
	}
	return false
}

// ComputeResponse contains the translated text
type ComputeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TranslatedText string                 `protobuf:"bytes,3,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ComputeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ComputeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComputeResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\n" +
	"translator\"\x0e\n" +
	"\fReadyRequest\"S\n" +
	"\rReadyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\";\n" +
	"\x0fPoweroffRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x05R\x04time\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"@\n" +
	"\x10PoweroffResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x0eComputeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x02 \x01(\bR\x04html\"h\n" +
	"\x0fComputeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ftranslated_text\x18\x03 \x01(\tR\x0etranslatedText2\xaa\x02\n" +
	"\x11TranslatorService\x12<\n" +
	"\x05Ready\x12\x18.translator.ReadyRequest\x1a\x19.translator.ReadyResponse\x12B\n" +
	"\aCompute\x12\x1a.translator.ComputeRequest\x1a\x1b.translator.ComputeResponse\x12L\n" +
	"\rComputeStream\x12\x1a.translator.ComputeRequest\x1a\x1b.translator.ComputeResponse(\x010\x01\x12E\n" +
	"\bPoweroff\x12\x1b.translator.PoweroffRequest\x1a\x1c.translator.PoweroffResponseB(Z&github.com/xxnuo/MTranCore/proto;protob\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_worker_proto_goTypes = []any{
	(*ReadyRequest)(nil),     // 0: translator.ReadyRequest
	(*ReadyResponse)(nil),    // 1: translator.ReadyResponse
	(*PoweroffRequest)(nil),  // 2: translator.PoweroffRequest
	(*PoweroffResponse)(nil), // 3: translator.PoweroffResponse
	(*ComputeRequest)(nil),   // 4: translator.ComputeRequest
	(*ComputeResponse)(nil),  // 5: translator.ComputeResponse
}
var file_proto_worker_proto_depIdxs = []int32{
	0, // 0: translator.TranslatorService.Ready:input_type -> translator.ReadyRequest
	4, // 1: translator.TranslatorService.Compute:input_type -> translator.ComputeRequest
	4, // 2: translator.TranslatorService.ComputeStream:input_type -> translator.ComputeRequest
	2, // 3: translator.TranslatorService.Poweroff:input_type -> translator.PoweroffRequest
	1, // 4: translator.TranslatorService.Ready:output_type -> translator.ReadyResponse
	5, // 5: translator.TranslatorService.Compute:output_type -> translator.ComputeResponse
	5, // 6: translator.TranslatorService.ComputeStream:output_type -> translator.ComputeResponse
	3, // 7: translator.TranslatorService.Poweroff:output_type -> translator.PoweroffResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
