// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslatorService_Health_FullMethodName        = "/translator.TranslatorService/Health"
	TranslatorService_Poweron_FullMethodName       = "/translator.TranslatorService/Poweron"
	TranslatorService_Poweroff_FullMethodName      = "/translator.TranslatorService/Poweroff"
	TranslatorService_Reboot_FullMethodName        = "/translator.TranslatorService/Reboot"
	TranslatorService_Ready_FullMethodName         = "/translator.TranslatorService/Ready"
	TranslatorService_Compute_FullMethodName       = "/translator.TranslatorService/Compute"
	TranslatorService_ComputeStream_FullMethodName = "/translator.TranslatorService/ComputeStream"
)

// TranslatorServiceClient is the client API for TranslatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TranslatorService provides translation capabilities
type TranslatorServiceClient interface {
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Poweron loads the translation engine with model files
	Poweron(ctx context.Context, in *PoweronRequest, opts ...grpc.CallOption) (*PoweronResponse, error)
	// Poweroff shuts down the server
	Poweroff(ctx context.Context, in *PoweroffRequest, opts ...grpc.CallOption) (*PoweroffResponse, error)
	// Reboot reloads the translation engine
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error)
	// Ready gets the current engine status
	Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
	// Compute translates a single text
	Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error)
	// ComputeStream translates multiple texts in streaming fashion
	ComputeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ComputeRequest, ComputeResponse], error)
}

type translatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslatorServiceClient(cc grpc.ClientConnInterface) TranslatorServiceClient {
	return &translatorServiceClient{cc}
}

func (c *translatorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Poweron(ctx context.Context, in *PoweronRequest, opts ...grpc.CallOption) (*PoweronResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoweronResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Poweron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Poweroff(ctx context.Context, in *PoweroffRequest, opts ...grpc.CallOption) (*PoweroffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoweroffResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Poweroff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebootResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeResponse)
	err := c.cc.Invoke(ctx, TranslatorService_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorServiceClient) ComputeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ComputeRequest, ComputeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslatorService_ServiceDesc.Streams[0], TranslatorService_ComputeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComputeRequest, ComputeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_ComputeStreamClient = grpc.BidiStreamingClient[ComputeRequest, ComputeResponse]

// TranslatorServiceServer is the server API for TranslatorService service.
// All implementations must embed UnimplementedTranslatorServiceServer
// for forward compatibility.
//
// TranslatorService provides translation capabilities
type TranslatorServiceServer interface {
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Poweron loads the translation engine with model files
	Poweron(context.Context, *PoweronRequest) (*PoweronResponse, error)
	// Poweroff shuts down the server
	Poweroff(context.Context, *PoweroffRequest) (*PoweroffResponse, error)
	// Reboot reloads the translation engine
	Reboot(context.Context, *RebootRequest) (*RebootResponse, error)
	// Ready gets the current engine status
	Ready(context.Context, *ReadyRequest) (*ReadyResponse, error)
	// Compute translates a single text
	Compute(context.Context, *ComputeRequest) (*ComputeResponse, error)
	// ComputeStream translates multiple texts in streaming fashion
	ComputeStream(grpc.BidiStreamingServer[ComputeRequest, ComputeResponse]) error
	mustEmbedUnimplementedTranslatorServiceServer()
}

// UnimplementedTranslatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslatorServiceServer struct{}

func (UnimplementedTranslatorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTranslatorServiceServer) Poweron(context.Context, *PoweronRequest) (*PoweronResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poweron not implemented")
}
func (UnimplementedTranslatorServiceServer) Poweroff(context.Context, *PoweroffRequest) (*PoweroffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poweroff not implemented")
}
func (UnimplementedTranslatorServiceServer) Reboot(context.Context, *RebootRequest) (*RebootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedTranslatorServiceServer) Ready(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedTranslatorServiceServer) Compute(context.Context, *ComputeRequest) (*ComputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedTranslatorServiceServer) ComputeStream(grpc.BidiStreamingServer[ComputeRequest, ComputeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ComputeStream not implemented")
}
func (UnimplementedTranslatorServiceServer) mustEmbedUnimplementedTranslatorServiceServer() {}
func (UnimplementedTranslatorServiceServer) testEmbeddedByValue()                           {}

// UnsafeTranslatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslatorServiceServer will
// result in compilation errors.
type UnsafeTranslatorServiceServer interface {
	mustEmbedUnimplementedTranslatorServiceServer()
}

func RegisterTranslatorServiceServer(s grpc.ServiceRegistrar, srv TranslatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedTranslatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslatorService_ServiceDesc, srv)
}

func _TranslatorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Poweron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoweronRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Poweron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Poweron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Poweron(ctx, req.(*PoweronRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Poweroff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoweroffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Poweroff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Poweroff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Poweroff(ctx, req.(*PoweroffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Ready(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslatorService_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).Compute(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslatorService_ComputeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslatorServiceServer).ComputeStream(&grpc.GenericServerStream[ComputeRequest, ComputeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslatorService_ComputeStreamServer = grpc.BidiStreamingServer[ComputeRequest, ComputeResponse]

// TranslatorService_ServiceDesc is the grpc.ServiceDesc for TranslatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translator.TranslatorService",
	HandlerType: (*TranslatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TranslatorService_Health_Handler,
		},
		{
			MethodName: "Poweron",
			Handler:    _TranslatorService_Poweron_Handler,
		},
		{
			MethodName: "Poweroff",
			Handler:    _TranslatorService_Poweroff_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _TranslatorService_Reboot_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _TranslatorService_Ready_Handler,
		},
		{
			MethodName: "Compute",
			Handler:    _TranslatorService_Compute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ComputeStream",
			Handler:       _TranslatorService_ComputeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/worker.proto",
}
