syntax = "proto3";

package translator;

option go_package = "github.com/xxnuo/MTranCore/proto;proto";

// TranslatorService provides translation capabilities
service TranslatorService {
  rpc Health(HealthRequest) returns (HealthResponse);

  rpc Trans(TransRequest) returns (TransResponse);

  rpc TransStream(stream TransRequest) returns (stream TransResponse);

  rpc Exit(ExitRequest) returns (ExitResponse);
}

message HealthRequest {}

message HealthResponse {
  int32 code = 1;
  string message = 2;
  bool ready = 3;
}

message TransRequest {
  string text = 1;
  bool html = 2;
}

message TransResponse {
  int32 code = 1;
  string message = 2;
  string translated_text = 3;
}

message ExitRequest {
  int32 time = 1;
  bool force = 2;
}

message ExitResponse {
  int32 code = 1;
  string message = 2;
}